CREATE TABLE IF NOT EXISTS asset_movements (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
    from_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    to_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    from_location_id BIGINT REFERENCES locations(id) ON DELETE RESTRICT,
    to_location_id BIGINT REFERENCES locations(id) ON DELETE RESTRICT,
    moved_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    movement_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);